dai:
    resource: "@DiktaplusBundle/Resources/config/routing.yml"
    prefix:   /dai/

api:
    resource: "@DiktaplusBundle/Resources/config/routing-api.yml"
    prefix:   /api/

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"