diktaplus:
    resource: "@DiktaplusBundle/Resources/config/routing.yml"
    prefix:   /

api:
    resource: "@DiktaplusBundle/Resources/config/routing-api.yml"
    prefix:   /api/

fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"