security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        auth:
            pattern: ^/*
            anonymous: ~
            provider: admins
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /
 
    providers:
        admins:
            entity: { class: DiktaplusBundle\Entity\Admin, property: email }
     
    access_control:
        - { path: ^/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY}
     
    encoders:
        DiktaplusBundle\Entity\Admin: { algorithm: sha512, iterations: 10 }