security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        auth:
            pattern: ^/*
            anonymous: ~
            provider: admins
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /

        oauth_token:
            pattern:  ^/oauth/v2/token
            security: false

        secured_area:
            pattern:    ^/
            fos_oauth:  true
            stateless:  true

    providers:
        admins:
            entity: { class: DiktaplusBundle\Entity\Admin, property: email }
        in_memory:
            memory: ~

    access_control:
        - { path: ^/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/api, roles: [ IS_AUTHENTICATED_FULLY ] }
     
    encoders:
        DiktaplusBundle\Entity\Admin: { algorithm: sha512, iterations: 10 }
