security:
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        auth:
            pattern: ^/(?!api)
            anonymous: ~
            provider: admins
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path: /logout
                target: /

        oauth_authorize:
            pattern:    ^/oauth/v2/auth
            form_login:
                provider: users
                check_path: vp_global_login_check
                login_path: vp_global_login
            anonymous: true
            context: test_connect

        oauth_token:
            pattern:  ^/oauth/v2/token
            security: false

        api:
            pattern:      ^/api(?!/users/register)
            fos_oauth:    true
            stateless:    true

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    providers:
        admins:
            entity: { class: DiktaplusBundle\Entity\Admin, property: email }
        users:
            id: diktaplus.user_provider
        in_memory:
            memory: ~

    access_control:
        - { path: ^/dai, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api, role: IS_AUTHENTICATED_FULLY }
     
    encoders:
        DiktaplusBundle\Entity\Admin: { algorithm: sha512, iterations: 10 }
        DiktaplusBundle\Entity\User: { algorithm: sha512, iterations: 10 }
