welcome:
    path:     /
    defaults: { _controller: DiktaplusBundle:Default:index }

texts:
    path:     /texts
    defaults: { _controller: DiktaplusBundle:Default:texts }

signup:
    pattern:  /signup
    defaults: { _controller: DiktaplusBundle:Default:signup }

login:
    pattern: /login
    defaults: { _controller: DiktaplusBundle:Default:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout