home:
    path:     /
    defaults: { _controller: DiktaplusBundle:Security:login }

welcome:
    path:     /welcome
    defaults: { _controller: DiktaplusBundle:Default:welcome }


#============================== TEXTS MANAGEMENT ============================

texts:
    path:     /texts
    defaults: { _controller: DiktaplusBundle:Texts:texts }

texts_add:
    path:     /texts/add
    defaults: { _controller: DiktaplusBundle:Texts:addText }

texts_edit:
    path:     /texts/edit{id}
    defaults: { _controller: DiktaplusBundle:Texts:editText }

texts_delete:
    path:     /texts/delete{id}
    defaults: { _controller: DiktaplusBundle:Texts:deleteText }


#============================== USERS MANAGEMENT ============================

users:
    path:     /users
    defaults: { _controller: DiktaplusBundle:Users:users }

users_add:
    path:     /usersadd
    defaults: { _controller: DiktaplusBundle:Users:addUser }

users_edit:
    path:     /usersedit{id}
    defaults: { _controller: DiktaplusBundle:Users:editUser }

users_delete:
    path:     /usersdelete{id}
    defaults: { _controller: DiktaplusBundle:Users:deleteUser }

#============================== SECURITY ============================

signup:
    pattern:  /signup
    defaults: { _controller: DiktaplusBundle:Security:signup }

login:
    pattern: /login
    defaults: { _controller: DiktaplusBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout