diktaplus_homepage:
    path:     /
    defaults: { _controller: DiktaplusBundle:Default:login }

diktaplus_signup:
    pattern:  /signup
    defaults: { _controller: DiktaplusBundle:Default:signup }
