post-user:
    path:     /users/add
    defaults: { _controller: DiktaplusBundle:API:postUser }
    methods:  POST

get-user:
    path:     /users/{id}
    defaults: { _controller: DiktaplusBundle:API:getUser }
    methods:  GET

put-user:
    path:     /users/{id}
    defaults: { _controller: DiktaplusBundle:API:putUser }
    methods:  PUT

delete-user:
    path:     /users/{id}
    defaults: { _controller: DiktaplusBundle:API:deleteUser }
    methods:  DELETE

get-texts:
    path:     /texts/{language}/{difficulty}
    defaults: { _controller: DiktaplusBundle:API:getTexts }
    methods:  GET



get-ranking:
    path:     /rankings/{country}/{cnt}
    defaults: { _controller: DiktaplusBundle:API:getRanking }
    methods:  GET

