register-user:
    path:     /users/add
    defaults: { _controller: DiktaplusBundle:API:registerUser }
    methods:  POST

login-user:
    path:     /users/login
    defaults: { _controller: DiktaplusBundle:API:loginUser }
    methods:  POST

get-user:
    path:     /users/{id}
    defaults: { _controller: DiktaplusBundle:API:getUser }
    methods:  GET

put-user:
    path:     /users/{id}
    defaults: { _controller: DiktaplusBundle:API:putUser }
    methods:  PUT

delete-user:
    path:     /users/{id}
    defaults: { _controller: DiktaplusBundle:API:deleteUser }
    methods:  DELETE

get-ranking:
    path:     /users/{country}/{cnt}
    defaults: { _controller: DiktaplusBundle:API:getRanking }
    methods:  GET

get-texts:
    path:     /texts/{language}/{difficulty}
    defaults: { _controller: DiktaplusBundle:API:getTexts }
    methods:  GET

post-game:
    path:     /games/add
    defaults: { _controller: DiktaplusBundle:API:postGame }
    methods:  POST

get-best-score:
    path:     /games/{user}/{text}
    defaults: { _controller: DiktaplusBundle:API:getBestScore }
    methods:  GET



