homepage:
    path:     /
    defaults: { _controller: DiktaplusBundle:Default:index }

welcome:
    path:     /welcome
    defaults: { _controller: DiktaplusBundle:Default:welcome }

signup:
    pattern:  /signup
    defaults: { _controller: DiktaplusBundle:Default:signup }

login:
  pattern: /login
  defaults: { _controller: DiktaplusBundle:Default:login }

login_check:
   pattern: /login_check

logout:
  pattern: /logout