welcome:
    path:     /
    defaults: { _controller: DiktaplusBundle:Default:index }

texts:
    path:     /texts
    defaults: { _controller: DiktaplusBundle:Texts:texts }

texts_add:
    path:     /texts/add/
    defaults: { _controller: DiktaplusBundle:Texts:addText }

texts_show:
    path:     /texts/show/{id}
    defaults: { _controller: DiktaplusBundle:Texts:showText }

texts_edit:
    path:     /texts/edit/{id}
    defaults: { _controller: DiktaplusBundle:Texts:editText }

texts_delete:
    path:     /texts/delete/{id}
    defaults: { _controller: DiktaplusBundle:Texts:deleteText }

signup:
    pattern:  /signup
    defaults: { _controller: DiktaplusBundle:Security:signup }

login:
    pattern: /login
    defaults: { _controller: DiktaplusBundle:Security:login }

login_check:
    pattern: /login_check

logout:
    pattern: /logout